/*

 BLUEWALL.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define BlueWallBank 0

/* Super Gameboy palette 0 */
#define BlueWallSGBPal0c0 6076
#define BlueWallSGBPal0c1 8935
#define BlueWallSGBPal0c2 6596
#define BlueWallSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define BlueWallSGBPal1c0 6076
#define BlueWallSGBPal1c1 8935
#define BlueWallSGBPal1c2 6596
#define BlueWallSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define BlueWallSGBPal2c0 6076
#define BlueWallSGBPal2c1 8935
#define BlueWallSGBPal2c2 6596
#define BlueWallSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define BlueWallSGBPal3c0 6076
#define BlueWallSGBPal3c1 8935
#define BlueWallSGBPal3c2 6596
#define BlueWallSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define BlueWallCGBPal0c0 32767
#define BlueWallCGBPal0c1 20544
#define BlueWallCGBPal0c2 10266
#define BlueWallCGBPal0c3 19478

/* Gameboy Color palette 1 */
#define BlueWallCGBPal1c0 6076
#define BlueWallCGBPal1c1 8935
#define BlueWallCGBPal1c2 6596
#define BlueWallCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define BlueWallCGBPal2c0 6076
#define BlueWallCGBPal2c1 8935
#define BlueWallCGBPal2c2 6596
#define BlueWallCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define BlueWallCGBPal3c0 6076
#define BlueWallCGBPal3c1 8935
#define BlueWallCGBPal3c2 6596
#define BlueWallCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define BlueWallCGBPal4c0 6076
#define BlueWallCGBPal4c1 8935
#define BlueWallCGBPal4c2 6596
#define BlueWallCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define BlueWallCGBPal5c0 6076
#define BlueWallCGBPal5c1 8935
#define BlueWallCGBPal5c2 6596
#define BlueWallCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define BlueWallCGBPal6c0 6076
#define BlueWallCGBPal6c1 8935
#define BlueWallCGBPal6c2 6596
#define BlueWallCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define BlueWallCGBPal7c0 6076
#define BlueWallCGBPal7c1 8935
#define BlueWallCGBPal7c2 6596
#define BlueWallCGBPal7c3 5344
/* CGBpalette entries. */
extern unsigned char BlueWallCGB[];
/* Start of tile array. */
extern unsigned char BlueWall[];

/* End of BLUEWALL.H */
