/*

 FALLDOWNSPRITES.H

 Include File.

 Info:
  Form                 : Each tile separate.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 4

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define BallStraightBank 0

/* Gameboy Color palette 0 */
#define BallStraightCGBPal0c0 32767
#define BallStraightCGBPal0c1 4090
#define BallStraightCGBPal0c2 6122
#define BallStraightCGBPal0c3 0

/* Gameboy Color palette 1 */
#define BallStraightCGBPal1c0 32767
#define BallStraightCGBPal1c1 31772
#define BallStraightCGBPal1c2 0
#define BallStraightCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define BallStraightCGBPal2c0 6076
#define BallStraightCGBPal2c1 8935
#define BallStraightCGBPal2c2 6596
#define BallStraightCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define BallStraightCGBPal3c0 6076
#define BallStraightCGBPal3c1 8935
#define BallStraightCGBPal3c2 6596
#define BallStraightCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define BallStraightCGBPal4c0 6076
#define BallStraightCGBPal4c1 8935
#define BallStraightCGBPal4c2 6596
#define BallStraightCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define BallStraightCGBPal5c0 6076
#define BallStraightCGBPal5c1 8935
#define BallStraightCGBPal5c2 6596
#define BallStraightCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define BallStraightCGBPal6c0 6076
#define BallStraightCGBPal6c1 8935
#define BallStraightCGBPal6c2 6596
#define BallStraightCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define BallStraightCGBPal7c0 6076
#define BallStraightCGBPal7c1 8935
#define BallStraightCGBPal7c2 6596
#define BallStraightCGBPal7c3 5344
/* CGBpalette entries. */
extern unsigned char BallStraightCGB[];
extern unsigned char BallStraightTLE0[];
extern unsigned char BallStraightTLE1[];
extern unsigned char BallStraightTLE2[];
extern unsigned char BallStraightTLE3[];
extern unsigned char BallStraightTLE4[];

/* End of FALLDOWNSPRITES.H */
