/*

 REDWALL.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 2

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define RedWallBank 0

/* Super Gameboy palette 0 */
#define RedWallSGBPal0c0 6076
#define RedWallSGBPal0c1 8935
#define RedWallSGBPal0c2 6596
#define RedWallSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define RedWallSGBPal1c0 6076
#define RedWallSGBPal1c1 8935
#define RedWallSGBPal1c2 6596
#define RedWallSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define RedWallSGBPal2c0 6076
#define RedWallSGBPal2c1 8935
#define RedWallSGBPal2c2 6596
#define RedWallSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define RedWallSGBPal3c0 6076
#define RedWallSGBPal3c1 8935
#define RedWallSGBPal3c2 6596
#define RedWallSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define RedWallCGBPal0c0 29662
#define RedWallCGBPal0c1 23
#define RedWallCGBPal0c2 8232
#define RedWallCGBPal0c3 13345

/* Gameboy Color palette 1 */
#define RedWallCGBPal1c0 6076
#define RedWallCGBPal1c1 8935
#define RedWallCGBPal1c2 6596
#define RedWallCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define RedWallCGBPal2c0 6076
#define RedWallCGBPal2c1 8935
#define RedWallCGBPal2c2 6596
#define RedWallCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define RedWallCGBPal3c0 6076
#define RedWallCGBPal3c1 8935
#define RedWallCGBPal3c2 6596
#define RedWallCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define RedWallCGBPal4c0 6076
#define RedWallCGBPal4c1 8935
#define RedWallCGBPal4c2 6596
#define RedWallCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define RedWallCGBPal5c0 6076
#define RedWallCGBPal5c1 8935
#define RedWallCGBPal5c2 6596
#define RedWallCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define RedWallCGBPal6c0 6076
#define RedWallCGBPal6c1 8935
#define RedWallCGBPal6c2 6596
#define RedWallCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define RedWallCGBPal7c0 6076
#define RedWallCGBPal7c1 8935
#define RedWallCGBPal7c2 6596
#define RedWallCGBPal7c3 5344
/* CGBpalette entries. */
extern unsigned char RedWallCGB[];
/* Start of tile array. */
extern unsigned char RedWall[];

/* End of REDWALL.H */
